import Course from "../models/Course.js";
import Lesson from "../models/Lesson.js";
import ContentSource from "../models/ContentSource.js";
import Assignment from "../models/Assignment.js";
import User from "../models/User.js";
import { createCourse } from "./courseService.js";
import { createLesson } from "./lessonService.js";
import cache from "../utils/cache.js";

const LICENSE_MAP = {
  internal: "internal",
  official_docs: "cc-by",
  open_education: "cc-by-sa",
};

async function resolveSystemTeacher() {
  let teacher = await User.findOne({ role: { $in: ["AI-TEACHER", "admin"] }, status: "approved" });
  if (!teacher) {
    teacher = await User.findOne({ role: "admin" });
  }
  if (!teacher) throw new Error("No system teacher available for generated courses");
  return teacher._id;
}

function estimateDuration(content) {
  const words = (content || "").split(/\s+/).length;
  return Math.max(5, Math.min(45, Math.ceil(words / 150)));
}

function formatLessonContent(lesson) {
  const parts = [lesson.content || ""];
  if (lesson.example) parts.push(`\n\n**Example:**\n${lesson.example}`);
  if (lesson.practiceTask) parts.push(`\n\n**Practice:**\n${lesson.practiceTask}`);
  return parts.join("");
}

export async function persistGeneratedCourse({
  syllabus,
  requestedBy,
  generationJobId,
  existingCourseId = null,
  partialLessons = [],
}) {
  const teacherId = await resolveSystemTeacher();
  const isMerge = Boolean(existingCourseId);

  let course;
  if (isMerge) {
    course = await Course.findById(existingCourseId);
    if (!course) throw new Error("Base course for merge not found");
    await Course.findByIdAndUpdate(existingCourseId, {
      description: syllabus.description || course.description,
      learningOutcomes: syllabus.learningOutcomes || course.learningOutcomes,
      estimatedWeeks: syllabus.estimatedWeeks || course.estimatedWeeks,
      prerequisites: syllabus.prerequisites || course.prerequisites,
      syllabusSnapshot: syllabus,
      tags: [...new Set([...(course.tags || []), ...(syllabus.tags || [])])],
    });
    course = await Course.findById(existingCourseId);
  } else {
    course = await createCourse({
      title: syllabus.title,
      description: syllabus.description,
      category: syllabus.category || "Other",
      teacher: teacherId,
      level: syllabus.level || "Beginner",
      price: 0,
      language: "English",
      isApproved: false,
      prerequisites: syllabus.prerequisites || [],
      tags: syllabus.tags || [syllabus.category].filter(Boolean),
      learningOutcomes: syllabus.learningOutcomes || [],
      estimatedWeeks: syllabus.estimatedWeeks || 4,
      isGenerated: true,
      generationJob: generationJobId,
      syllabusSnapshot: syllabus,
    });
  }

  const sourceIds = [];
  let orderOffset = 0;

  if (isMerge) {
    const existingCount = await Lesson.countDocuments({ course: course._id });
    orderOffset = existingCount;
  }

  for (const partial of partialLessons) {
    if (partial.lessonId) {
      await Lesson.findByIdAndUpdate(partial.lessonId, { course: course._id });
    }
  }

  let lessonOrder = orderOffset;
  for (const mod of syllabus.modules || []) {
    for (const lesson of mod.lessons || []) {
      lessonOrder += 1;
      const content = formatLessonContent(lesson);
      const savedLesson = await createLesson({
        course: course._id,
        title: lesson.title,
        content,
        moduleTitle: mod.title,
        objectives: lesson.objectives || [],
        example: lesson.example,
        practiceTask: lesson.practiceTask,
        quiz: lesson.quiz || [],
        duration: estimateDuration(content),
        order: lessonOrder,
      });

      const aiSource = await ContentSource.create({
        title: `AI-generated: ${lesson.title}`,
        sourceType: "ai_generated",
        licenseType: "internal",
        attribution: "MR5 School AI Curriculum Architect",
        course: course._id,
        lesson: savedLesson._id,
        notes: "Original instructional material generated by MR5 School AI",
      });
      sourceIds.push(aiSource._id);
    }
  }

  for (const link of syllabus.resourceLinks || []) {
    const source = await ContentSource.create({
      title: link.title,
      url: link.url,
      sourceType: link.licenseType === "official_docs" ? "official_docs" : "open_education",
      licenseType: LICENSE_MAP[link.licenseType] || "cc-by",
      attribution: link.title,
      course: course._id,
      notes: "Referenced resource — content transformed into original instructional material",
    });
    sourceIds.push(source._id);
  }

  if (syllabus.finalProject?.title) {
    await Assignment.create({
      course: course._id,
      teacher: teacherId,
      title: syllabus.finalProject.title,
      description: [
        syllabus.finalProject.brief,
        "",
        "Rubric:",
        ...(syllabus.finalProject.rubric || []).map((r) => `- ${r}`),
      ].join("\n"),
      dueDate: new Date(Date.now() + (syllabus.estimatedWeeks || 4) * 7 * 24 * 60 * 60 * 1000),
    });
  }

  cache.clear();

  return { course, sourceIds, lessonCount: lessonOrder - orderOffset };
}

export function buildMergeSyllabus(baseSyllabus, existingLessons, intent) {
  const existingTitles = new Set(
    (existingLessons || []).map((l) => l.title?.toLowerCase()),
  );

  const filteredModules = (baseSyllabus.modules || []).map((mod) => ({
    ...mod,
    lessons: (mod.lessons || []).filter(
      (lesson) => !existingTitles.has(lesson.title?.toLowerCase()),
    ),
  })).filter((mod) => mod.lessons.length > 0);

  return {
    ...baseSyllabus,
    title: baseSyllabus.title || `${intent.topic} — Complete Path`,
    modules: filteredModules,
  };
}
